### ISSUE TITLE
2016 results issues

### ISSUE THREAD

**Issue by BrianAmos** [openelections/openelections-data-ut#30]
- [x] Cache County - mixed up votes outside of Logan in inconsistent ways, this looks like it would almost take someone redoing the work from scratch.

- [x] Daggett County - for the presidential results, the county totals are used for Manila instead of the correct numbers.

Davis County - mistranscribed votes:
- [x] Trump in Hill AFB 1
- [x] McMullin in Bountiful 7+8, Farmington 5
- [x] Governor-Herbert in Farmington 12
- [x] Attorney General-Reyes in Farmington 3
- [x] Attorney General-Harper in North Salt Lake 2
- [x] I still get more discrepancies in Reyes and Harper (ATG) 
- [x] Dougall (AUD), but I can't find them easily.

- [x] Emery County - missing "Canvas" votes.

Millard County - mistranscribed votes:
- [x] Trump in ABR14.
- [x] Treasurer-Hansen in KAN4.
- [x] Governor-Weinholtz in GAR16.
- [x] Almost all governor votes for HOLD8.

**Comment by dwillis** [comment]
@BrianAmos Have fixed all but Cache, which is in progress.

**Comment by dwillis** [comment]
@BrianAmos this is done and the statewide file has been regenerated.
