### ISSUE TITLE
TYPO: Kane County 2016 Presidential Race: Votes for Moorehead and McMullin switched

### ISSUE THREAD

**Issue by peter-redistricting-data-hub** [openelections/openelections-data-ut#65]
Can see that the results are switched from looking here: 

https://github.com/openelections/openelections-sources-ut/blob/master/2016%20General%20Election/SOVC%20-%20Kane.pdf

and comparing to:

https://raw.githubusercontent.com/openelections/openelections-data-ut/master/2016/20161108__ut__general__precinct.csv

**Comment by dwillis** [comment]
@peter-redistricting-data-hub This is fixed now, thanks!
