### ISSUE TITLE
20161108__ut__general__precinct.csv file Davis County - Bountiful 7 Moorehead and McMullin Votes Switched

### ISSUE THREAD

**Issue by peter-redistricting-data-hub** [openelections/openelections-data-ut#66]
https://github.com/openelections/openelections-sources-ut/blob/master/2016%20General%20Election/SOVC%20-%20Davis.pdf

McMullin should have 166 and Moorehead should have 1

**Comment by dwillis** [comment]
@peter-redistricting-data-hub This is fixed now, thanks!
