### ISSUE TITLE
2016/20161108__ut__general__precinct.csv TYPOs: Cache - Hyrum 03 Presidential Results 

### ISSUE THREAD

**Issue by peter-redistricting-data-hub** [openelections/openelections-data-ut#67]
Page 32: https://github.com/openelections/openelections-sources-ut/blob/master/2016%20General%20Election/SOVC%20-%20Cache.pdf as an example for Jill Stein

It seems like the results in the Cache County file are correct, and for whatever reason, in the compiled file the numbers are different (at a glance, it looks like the total votes sometimes was substituted for absentee or mail or election day votes, or sometimes had those votes subtracted)

**Comment by dwillis** [comment]
@peter-redistricting-data-hub This is fixed now, thanks!
